---
deployment:
  tasks:
    - export DEPLOYPATH=/home/laflot6/filemanagerapp
    - /bin/cp -r config csv db firebase loaders mailing middleware migration models routes sequelize services third-party-api tmp utils app.js .env fbAdminKeys.json server.js package.json $DEPLOYPATH